### ISSUE TITLE
FOTA

### ISSUE THREAD

**Issue by rbrondi** [STMicroelectronics/BlueSTSDK_Android#15]
Hi all,
We are developing an Android application that interacts with SensorTile (STEVALSTLKT01V1) boards through the BlueSTSDK library. In our project we want to use the SensorTile soldered on the STEVAL-STLCR01V1 cradle board. We have downloaded and customized the FP-SNS-ALLMEMS1 firmware. The FP-SNS-ALLMEMS1 documentation states that board firmware can be updated over the air through Bluetooth but it is not clear to me if this is true only for a limited set of ST boards. Is it possible to use FOTA to update SensorTile boards?

Looking at the documentation, it is also said that  BlueMS application can use FOTA to update  X-NUCLEO-IDB05A1 board. Can BlueMS be used to update also SensorTile boards? 
BlueSTSDK offers this option? Is there an example on how to use FOTA in BlueSTSDK?
Thanks a lot.

**Comment by GiovanniVisentiniST** [comment]
Hi,

yes the FOTA is supported by the SensorTile (that has the same BLE chip of the IDB05A1 boards).
The FOTA is build on to of the Debug console.
You can find all the app code here: [BlueSTSDK_GUI_Android](https://github.com/STMicroelectronics-CentralLabs/BlueSTSDK_GUI_Android/tree/master/src/main/java/com/st/BlueSTSDK/gui/fwUpgrade)
the protocol is implemeted here: [FwUpgradeConsoleNucleo](https://github.com/STMicroelectronics-CentralLabs/BlueSTSDK_GUI_Android/blob/master/src/main/java/com/st/BlueSTSDK/gui/fwUpgrade/fwUpgradeConsole/FwUpgradeConsoleNucleo.java#L66)

I close this issue, please open a new one in the BlueSTSDK_GUI_Android repository if you have further questions.

Best Regards
Giovanni
