### ISSUE TITLE
Error on mNode.isConnected

### ISSUE THREAD

**Issue by ArthurKun21** [STMicroelectronics/BlueSTSDK_Android#20]
i seem to be getting error when i have reached the mNode.isConnected. The App just crash  
  
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.st.BlueSTSDK.Node.isConnected()' on a null object reference  
  
Please correct me if i am wrong but i need to use the ST BLE sensor in the playstore to upload firmware, or is there any other way?  
  
my board is STEVAL-MKSBOX1V1 (SensorTile.Box )   
  
sorry for the trouble

**Comment by GiovanniVisentiniST** [comment]
well your mNode is null.

do you have the error in our apps?

yes to upgrade the SensorTile.box you have to use the official ST BLE Sensor apps, the code to download the new firmware is not public.

Best Regards
Giovanni

**Comment by ArthurKun21** [comment]
@GiovanniVisentini i am actually trying to convert the listview to recyclerview  
  
but on the other question for the firmware, I actually have STLINK V3SET and STEVAL-MKSBOX1V1(SensorTile.Box), would like to ask if how can i flash the FP-Ai-sensing (https://my.st.com/content/my_st_com/en/products/embedded-software/mcu-mpu-embedded-software/stm32-embedded-software/stm32-ode-function-pack-sw/fp-ai-sensing1.html) or other firmware and change some details on what feature that can be shown in the android app. And as well if there is instructions/documentations on how to connect the SensorTile.Box and STLINK-V3SET

If there is any existing documentation, it would be great

**Comment by GiovanniVisentiniST** [comment]
Hi,

The SensorTile.box and the STLink v3 are not compatible, they have different voltage. 
An adapter will be available in the next months.

The FP-AI-SENSING1 v3.0.0 has the bootloader that is not compatible with the default firmware.
so you have to use the ST Link v2 to flash the bootloader and the fw or  you can try to: 

1.  power off the board

2.  hold down the boot button while connect the USB cable

3.now the board is in DFU Mode, you can the STM32 Programmer  tool to connect to it

4. dump the flash to have a copy of the current fw 

5. flesh the new fw and bootloader

Best Regards
