### ISSUE TITLE
PDR SDK?

### ISSUE THREAD

**Issue by dule-hwp** [STMicroelectronics/BlueSTSDK_Android#4]
Hi,

Not quite sure that this question should be asked here, but i dont know where else to ask it..

I have seen this video about PDR SDK a while ago. https://www.youtube.com/watch?v=vObyJ7rG93E

Is the dead reckoning SDK available? If yes, could you share the link please? If not, is there any timeframe of when it might become available?

Thank you

**Comment by GiovanniVisentiniST** [comment]
Hi Dusan,

We don't have plans to add the PDR to the SDK at the moment. 
I don't have infos about the libs. Probably the best place where ask the question is this one: [St Community: Mems And Sensor](https://community.st.com/community/mems-sensors-community)

Regards
Giovanni
